baseURL = 'https://bastidesaintpierrenoyer.fr/'
theme = 'graysx'
title = 'Bastide Saint-Pierre Noyer'

defaultContentLanguage = 'fr'
locale = 'fr-fr'

[languages]
  [languages.fr]
    label = 'Français'
    weight = 1
  [languages.en]
    label = 'English'
    weight = 2

[params]
logo = "/assets/img/logo.webp"
favicon = "assets/favicon.png"
address = "Quartier Saint-Pierre, 83640 Saint-Zacharie"
phone = ""
defaultLang = "fr"

[menu]
  [[menu.main]]
    identifier = "about"
    url = "#about"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    url = "#projects"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    url = "#signup"
    weight = 30
